{
  config,
  ...
}:
{
  services.tailscaleProxy.tailnetDomain = "follow-bigeye.ts.net";

  networking.hostName = "juniper-srv-vm";
  networking.hostId = "8425e349";

  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.devNodes = "/dev";
  boot.zfs.requestEncryptionCredentials = [ "rpool" ];

  # fileSystems and swapDevices are generated by disko (see disko.nix)

  services.zfs.autoScrub.enable = true;
  services.zfs.autoSnapshot.enable = true;
  services.zfs.trim.enable = true;

  users.users.${config.mySystem.username}.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHWMOaV5XRTqvw5iOFV3P+4m/dgannp8OQpSJmP7GXYO u7591yj@aspen-lap-lavie"
  ];

  security.sudo.wheelNeedsPassword = true;

  system.stateVersion = "25.11";
}
